### ISSUE TITLE
Batch Verification not working 

### ISSUE THREAD

**Issue by spatelamit** [reacherhq/reacher-js#185]
[user@ip-10-10-1-209 examples]$ ../node_modules/.bin/ts-node csv_batch.ts
/home/user/public_html/amit/reacher-js/examples/csv_batch.ts:43
                q.push(data.map((email) => ({ to_email: email }))).catch(console.error);
                                                          ^
TypeError: q.push(...).catch is not a function
    at Parser.<anonymous> (/home/user/public_html/amit/reacher-js/examples/csv_batch.ts:43:59)
    at Parser.emit (events.js:314:20)
    at Parser.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Parser.Readable.push (_stream_readable.js:213:10)
    at Parser.Transform.push (_stream_transform.js:152:32)
    at Parser.__push (/home/user/public_html/amit/reacher-js/node_modules/csv-parse/lib/index.js:965:10)
    at Parser.__onRecord (/home/user/public_html/amit/reacher-js/node_modules/csv-parse/lib/index.js:886:28)
    at Parser.__parse (/home/user/public_html/amit/reacher-js/node_modules/csv-parse/lib/index.js:668:38)
[user@ip-10-10-1-209 examples]$

**Comment by amaurym** [comment]
close by #186 and released in 0.3.0
